version: "3.8"

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: owasp-demo-backend
    environment:
      NODE_ENV: development
      PORT: 3001
      JWT_SECRET: dev-secret-key-change-in-production
      SESSION_SECRET: dev-session-secret-change-in-production
      CORS_ORIGIN: http://localhost:3000
      ENABLE_VULNERABLE_ENDPOINTS: "true"
    ports:
      - "3001:3001"
    volumes:
      - ./backend/src:/app/src
    command: npm run dev
    networks:
      - owasp-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3001
    container_name: owasp-demo-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - owasp-network

  # Attacker (for cross-origin attacks demo)
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: owasp-demo-attacker
    environment:
      PORT: 8080
      BACKEND_URL: http://backend:3001
    ports:
      - "3002:8080"
    depends_on:
      - backend
    networks:
      - owasp-network

networks:
  owasp-network:
    driver: bridge
